apiVersion: v1
appVersion: 0.0.1
description: A Helm chart to deploy Fibonacci
name: Fibonacci
version: 0.1.0
maintainers:
  - name: Decipher Technology Studios Engineering
    email: engineering@deciphernow.com
    website: deciphernow.com
keywords:
  - Grey Matter
  - service mesh
